"""add times field for user

Revision ID: 3fb8b2ffe05d
Revises: f1ca736741e8
Create Date: 2025-11-29 20:26:42.976515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb8b2ffe05d'
down_revision: Union[str, None] = 'f1ca736741e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default="NOW()"))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default="NOW()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
